function AssembleSimData(save_filename, fDATA)

% Load Simulation Information Created by GenKWaveSimInfo.m
siminfo_filename = ['sim_info/', save_filename];
load(siminfo_filename);

% Fourier Transform and Inverse
[T, F] = meshgrid(time, freq);
[TR, FR] = meshgrid(time, fDATA);
FT = exp(-1i*2*pi*F.*T)*mean(diff(time));
FTR = exp(-1i*2*pi*FR.*TR)*mean(diff(time));
IFT = exp(1i*2*pi*F'.*T')*mean(diff(freq));
IFTR = exp(1i*2*pi*FR'.*TR')*mean(diff(fDATA));
Resamp = FTR*IFT; % Fourier Resampling

% Assemble Full Dataset
full_dataset = zeros(numel(fDATA), numElemPerRow, numRows, ... % Receivers
    numElemPerRow, 'single'); % Transmitters
for tx_idx = 1:numElemPerRow
    % Load Full Synthetic Aperture Data Generated by k-Wave
    filename = ['sim_data/rf_data_tx_', num2str(tx_idx), '.mat'];
    load(filename, 'rf_data_FT'); % File Has Been Saved
    % Resample the Data in Frequency Domain
    full_dataset(:,:,:,tx_idx) = pagemtimes(Resamp, rf_data_FT);
    disp(['Data for Cylindrical Wave TX ', num2str(tx_idx), ' has been assembled']);
end

% Save Dataset
dataset_filename = ['datasets/', save_filename];
save(dataset_filename, '-v7.3', 'full_dataset', 'fDATA'); % File Has Been Saved

end