clear
clc

% Load Simulation Information Created by GenKWaveSimInfo.m
siminfo_filename = 'sim_info/LeftBreastMRI.mat';
load(siminfo_filename);

%% Which Simulation to Load
tx_idx = 1;

% Load Full Synthetic Aperture Data Generated by k-Wave
filename = ['sim_data/rf_data_tx_', num2str(tx_idx), '.mat'];
load(filename, 'rf_data_FT'); % File Has Been Saved

% Frequency Axis for Resampling
df = 2.5e3; fmax = max(freq);
freqResamp = df:df:fmax;

% Fourier Transform and Inverse
[T, F] = meshgrid(time, freq);
[TR, FR] = meshgrid(time, freqResamp);
FT = exp(-1i*2*pi*F.*T)*mean(diff(time));
FTR = exp(-1i*2*pi*FR.*TR)*mean(diff(time));
IFT = exp(1i*2*pi*F'.*T')*mean(diff(freq));
IFTR = exp(1i*2*pi*FR'.*TR')*mean(diff(freqResamp));

% Resample the Data in Frequency Domain
Resamp = FTR*IFT; % Fourier Resampling
rf_data_FT_Resamp = pagemtimes(Resamp, rf_data_FT);

% Compute Time-Domain Channel Data
rf_data = pagemtimes(IFTR, rf_data_FT_Resamp);

%% Visualize Result
dispRange = [-1,1]*(1e-3);
rx_row = 1; % Initiate Loop
while true
    rx_row = mod(rx_row,numRows)+1;
    imagesc(1:numElemPerRow, (1e6)*time, ...
        real(rf_data(:,:,rx_row)), dispRange); 
    xlabel('Element'); ylabel('Time (\mus)'); 
    title(['Received Data from Row ', num2str(rx_row)]); drawnow;
end